/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    LotFactory: {
      address:
        "0x17b2fc20d74815510c0b88b94b2448292e465a0a31ef3bb05b40989ef585257",
      abi: [
        {
          type: "impl",
          name: "LotFactoryImpl",
          interface_name: "contracts::lot_factory::ILotFactory",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::internal::bounded_int::BoundedInt::<0, 30>",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::lot_factory::Lot",
          members: [
            {
              name: "issuer",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "status",
              type: "core::integer::u8",
            },
            {
              name: "total_shares",
              type: "core::integer::u256",
            },
            {
              name: "initial_price_per_share",
              type: "core::integer::u256",
            },
            {
              name: "metadata_hash",
              type: "core::felt252",
            },
            {
              name: "created_at",
              type: "core::integer::u64",
            },
            {
              name: "total_initial_weight_grams",
              type: "core::integer::u32",
            },
            {
              name: "total_current_weight_grams",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::lot_factory::ILotFactory",
          items: [
            {
              type: "function",
              name: "create_lot",
              inputs: [
                {
                  name: "issuer",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "total_shares",
                  type: "core::integer::u256",
                },
                {
                  name: "initial_price_per_share",
                  type: "core::integer::u256",
                },
                {
                  name: "metadata_hash",
                  type: "core::felt252",
                },
                {
                  name: "token_name",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "token_symbol",
                  type: "core::byte_array::ByteArray",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_lot_status",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "new_status",
                  type: "core::integer::u8",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_lot_initial_weight",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "weight_grams",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_lot_current_weight",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "weight_grams",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_protocol_operator",
              inputs: [
                {
                  name: "new_operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_settlement_registry",
              inputs: [
                {
                  name: "settlement_registry",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_shares_token_class_hash",
              inputs: [
                {
                  name: "class_hash",
                  type: "core::starknet::class_hash::ClassHash",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_lot",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "contracts::lot_factory::Lot",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_status",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_initial_price_per_share",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_shares_token",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_next_lot_id",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_protocol_operator",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_settlement_registry",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_shares_token_class_hash",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::class_hash::ClassHash",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_initial_weight",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_current_weight",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_weight_gain",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_interfaces::access::ownable::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_interfaces::access::ownable::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "protocol_operator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "shares_token_class_hash",
              type: "core::starknet::class_hash::ClassHash",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::lot_factory::LotFactory::LotCreated",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "issuer",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "total_shares",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "initial_price_per_share",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "metadata_hash",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "shares_token",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "created_at",
              type: "core::integer::u64",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::lot_factory::LotFactory::LotStatusChanged",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "old_status",
              type: "core::integer::u8",
              kind: "data",
            },
            {
              name: "new_status",
              type: "core::integer::u8",
              kind: "data",
            },
            {
              name: "changed_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::lot_factory::LotFactory::LotWeightUpdated",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "weight_type",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "old_weight_grams",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "new_weight_grams",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "updated_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::lot_factory::LotFactory::ProtocolOperatorUpdated",
          kind: "struct",
          members: [
            {
              name: "old_operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "updated_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::lot_factory::LotFactory::SettlementRegistryUpdated",
          kind: "struct",
          members: [
            {
              name: "old_registry",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_registry",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "updated_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::lot_factory::LotFactory::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "LotCreated",
              type: "contracts::lot_factory::LotFactory::LotCreated",
              kind: "nested",
            },
            {
              name: "LotStatusChanged",
              type: "contracts::lot_factory::LotFactory::LotStatusChanged",
              kind: "nested",
            },
            {
              name: "LotWeightUpdated",
              type: "contracts::lot_factory::LotFactory::LotWeightUpdated",
              kind: "nested",
            },
            {
              name: "ProtocolOperatorUpdated",
              type: "contracts::lot_factory::LotFactory::ProtocolOperatorUpdated",
              kind: "nested",
            },
            {
              name: "SettlementRegistryUpdated",
              type: "contracts::lot_factory::LotFactory::SettlementRegistryUpdated",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0xb64117ec130b5e7165eadcda751ed3924f65544b7aa0bb1513e1794a389bdb",
    },
    AnimalRegistry: {
      address:
        "0x94dbc6ebe165c7cd62d4d56bd6e047e34a214485e5870257b335843279793c",
      abi: [
        {
          type: "impl",
          name: "AnimalRegistryImpl",
          interface_name: "contracts::animal_registry::IAnimalRegistry",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<(core::integer::u256, core::integer::u32)>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<(core::integer::u256, core::integer::u32)>",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::starknet::contract_address::ContractAddress>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::starknet::contract_address::ContractAddress>",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::integer::u256>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::integer::u256>",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::animal_registry::Animal",
          members: [
            {
              name: "custodian",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "status",
              type: "core::integer::u8",
            },
            {
              name: "current_lot_id",
              type: "core::integer::u256",
            },
            {
              name: "profile_hash",
              type: "core::felt252",
            },
            {
              name: "created_at",
              type: "core::integer::u64",
            },
            {
              name: "initial_weight_grams",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::animal_registry::IAnimalRegistry",
          items: [
            {
              type: "function",
              name: "register_animal",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
                {
                  name: "custodian",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "profile_hash",
                  type: "core::felt252",
                },
                {
                  name: "initial_weight_grams",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "register_animal_batch",
              inputs: [
                {
                  name: "animals_with_weights",
                  type: "core::array::Span::<(core::integer::u256, core::integer::u32)>",
                },
                {
                  name: "custodians",
                  type: "core::array::Span::<core::starknet::contract_address::ContractAddress>",
                },
                {
                  name: "profile_hashes",
                  type: "core::array::Span::<core::felt252>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "assign_to_lot",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "assign_to_lot_batch",
              inputs: [
                {
                  name: "animal_ids",
                  type: "core::array::Span::<core::integer::u256>",
                },
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "remove_from_lot",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "remove_from_lot_batch",
              inputs: [
                {
                  name: "animal_ids",
                  type: "core::array::Span::<core::integer::u256>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_animal_status",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
                {
                  name: "new_status",
                  type: "core::integer::u8",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_animal_status_batch",
              inputs: [
                {
                  name: "animal_ids",
                  type: "core::array::Span::<core::integer::u256>",
                },
                {
                  name: "new_status",
                  type: "core::integer::u8",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "transfer_custody",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
                {
                  name: "new_custodian",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_protocol_operator",
              inputs: [
                {
                  name: "new_operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_lot_factory",
              inputs: [
                {
                  name: "new_lot_factory",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_animal",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "contracts::animal_registry::Animal",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_custodian",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_animal_status",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u8",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_current_lot",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_animal_count",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "animal_exists",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_protocol_operator",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_factory",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_animal_initial_weight",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "owner_of",
              inputs: [
                {
                  name: "token_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "balance_of",
              inputs: [
                {
                  name: "owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_interfaces::access::ownable::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_interfaces::access::ownable::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "protocol_operator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "lot_factory",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_security::reentrancyguard::ReentrancyGuardComponent::Event",
          kind: "enum",
          variants: [],
        },
        {
          type: "event",
          name: "contracts::animal_registry::AnimalRegistry::AnimalRegistered",
          kind: "struct",
          members: [
            {
              name: "animal_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "custodian",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "profile_hash",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "created_at",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "initial_weight_grams",
              type: "core::integer::u32",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::animal_registry::AnimalRegistry::AnimalAssigned",
          kind: "struct",
          members: [
            {
              name: "animal_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "assigned_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::animal_registry::AnimalRegistry::AnimalRemoved",
          kind: "struct",
          members: [
            {
              name: "animal_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "removed_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::animal_registry::AnimalRegistry::AnimalStatusChanged",
          kind: "struct",
          members: [
            {
              name: "animal_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "old_status",
              type: "core::integer::u8",
              kind: "data",
            },
            {
              name: "new_status",
              type: "core::integer::u8",
              kind: "data",
            },
            {
              name: "changed_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::animal_registry::AnimalRegistry::CustodyTransferred",
          kind: "struct",
          members: [
            {
              name: "animal_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "from",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "to",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::animal_registry::AnimalRegistry::ProtocolOperatorUpdated",
          kind: "struct",
          members: [
            {
              name: "old_operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "updated_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::animal_registry::AnimalRegistry::LotFactoryUpdated",
          kind: "struct",
          members: [
            {
              name: "old_factory",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_factory",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "updated_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::animal_registry::AnimalRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "ReentrancyGuardEvent",
              type: "openzeppelin_security::reentrancyguard::ReentrancyGuardComponent::Event",
              kind: "flat",
            },
            {
              name: "AnimalRegistered",
              type: "contracts::animal_registry::AnimalRegistry::AnimalRegistered",
              kind: "nested",
            },
            {
              name: "AnimalAssigned",
              type: "contracts::animal_registry::AnimalRegistry::AnimalAssigned",
              kind: "nested",
            },
            {
              name: "AnimalRemoved",
              type: "contracts::animal_registry::AnimalRegistry::AnimalRemoved",
              kind: "nested",
            },
            {
              name: "AnimalStatusChanged",
              type: "contracts::animal_registry::AnimalRegistry::AnimalStatusChanged",
              kind: "nested",
            },
            {
              name: "CustodyTransferred",
              type: "contracts::animal_registry::AnimalRegistry::CustodyTransferred",
              kind: "nested",
            },
            {
              name: "ProtocolOperatorUpdated",
              type: "contracts::animal_registry::AnimalRegistry::ProtocolOperatorUpdated",
              kind: "nested",
            },
            {
              name: "LotFactoryUpdated",
              type: "contracts::animal_registry::AnimalRegistry::LotFactoryUpdated",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0xfa3703a79342ce32180056a4dde4c76f92406df3e2ab9bc9ecb80c9a89fa15",
    },
    TraceabilityOracle: {
      address:
        "0x467b23505cd4e2c194fd0e21524a13ea944b8daf077005334182649bb391517",
      abi: [
        {
          type: "impl",
          name: "TraceabilityOracleImpl",
          interface_name: "contracts::traceability_oracle::ITraceabilityOracle",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::integer::u256>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::integer::u256>",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::integer::u32>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::integer::u32>",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::traceability_oracle::TraceAnchor",
          members: [
            {
              name: "root",
              type: "core::felt252",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
            },
            {
              name: "event_count",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::traceability_oracle::ITraceabilityOracle",
          items: [
            {
              type: "function",
              name: "anchor_trace",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
                {
                  name: "root",
                  type: "core::felt252",
                },
                {
                  name: "event_count",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "anchor_trace_batch",
              inputs: [
                {
                  name: "animal_ids",
                  type: "core::array::Span::<core::integer::u256>",
                },
                {
                  name: "roots",
                  type: "core::array::Span::<core::felt252>",
                },
                {
                  name: "event_counts",
                  type: "core::array::Span::<core::integer::u32>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "correct_trace",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
                {
                  name: "new_root",
                  type: "core::felt252",
                },
                {
                  name: "new_event_count",
                  type: "core::integer::u32",
                },
                {
                  name: "correction_reason",
                  type: "core::felt252",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_attestor",
              inputs: [
                {
                  name: "new_attestor",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_last_root",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_last_timestamp",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_trace_anchor",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "contracts::traceability_oracle::TraceAnchor",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_attestor",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_correction_count",
              inputs: [
                {
                  name: "animal_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u32",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_interfaces::access::ownable::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_interfaces::access::ownable::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "attestor",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::traceability_oracle::TraceabilityOracle::AnimalTraceAnchored",
          kind: "struct",
          members: [
            {
              name: "animal_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "root",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "event_count",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "attestor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::traceability_oracle::TraceabilityOracle::AnimalTraceCorrected",
          kind: "struct",
          members: [
            {
              name: "animal_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "old_root",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "new_root",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "new_event_count",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "correction_reason",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "correction_number",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "attestor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::traceability_oracle::TraceabilityOracle::AttestorChanged",
          kind: "struct",
          members: [
            {
              name: "old_attestor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_attestor",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "changed_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::traceability_oracle::TraceabilityOracle::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "AnimalTraceAnchored",
              type: "contracts::traceability_oracle::TraceabilityOracle::AnimalTraceAnchored",
              kind: "nested",
            },
            {
              name: "AnimalTraceCorrected",
              type: "contracts::traceability_oracle::TraceabilityOracle::AnimalTraceCorrected",
              kind: "nested",
            },
            {
              name: "AttestorChanged",
              type: "contracts::traceability_oracle::TraceabilityOracle::AttestorChanged",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x46a6478609f9114304a247d1d604ba829fa7c72ef8593827f826e87cbbc8922",
    },
    SettlementRegistry: {
      address:
        "0x6f3096b3bacc902ec54a9030643a23f08d4ad9dc5c6911baaba49b8da1e9419",
      abi: [
        {
          type: "impl",
          name: "SettlementRegistryImpl",
          interface_name: "contracts::settlement_registry::ISettlementRegistry",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::settlement_registry::Settlement",
          members: [
            {
              name: "settled_at",
              type: "core::integer::u64",
            },
            {
              name: "final_report_hash",
              type: "core::felt252",
            },
            {
              name: "total_proceeds",
              type: "core::integer::u256",
            },
            {
              name: "settled_by",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "final_total_weight_grams",
              type: "core::integer::u32",
            },
            {
              name: "final_average_weight_grams",
              type: "core::integer::u32",
            },
            {
              name: "initial_total_weight_grams",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::settlement_registry::WeightStats",
          members: [
            {
              name: "initial_weight_grams",
              type: "core::integer::u32",
            },
            {
              name: "final_weight_grams",
              type: "core::integer::u32",
            },
            {
              name: "weight_gain_grams",
              type: "core::integer::u32",
            },
            {
              name: "weight_gain_percentage",
              type: "core::integer::u16",
            },
            {
              name: "days_in_feedlot",
              type: "core::integer::u64",
            },
            {
              name: "avg_daily_gain_grams",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::settlement_registry::ISettlementRegistry",
          items: [
            {
              type: "function",
              name: "settle_lot",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
                {
                  name: "final_report_hash",
                  type: "core::felt252",
                },
                {
                  name: "total_proceeds",
                  type: "core::integer::u256",
                },
                {
                  name: "final_total_weight_grams",
                  type: "core::integer::u32",
                },
                {
                  name: "final_average_weight_grams",
                  type: "core::integer::u32",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_protocol_operator",
              inputs: [
                {
                  name: "new_operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_lot_factory",
              inputs: [
                {
                  name: "new_lot_factory",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_settlement",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "contracts::settlement_registry::Settlement",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_settled",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_factory",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_protocol_operator",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_lot_weight_stats",
              inputs: [
                {
                  name: "lot_id",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "contracts::settlement_registry::WeightStats",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_interfaces::access::ownable::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_interfaces::access::ownable::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "protocol_operator",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "lot_factory",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_security::reentrancyguard::ReentrancyGuardComponent::Event",
          kind: "enum",
          variants: [],
        },
        {
          type: "event",
          name: "contracts::settlement_registry::SettlementRegistry::LotSettled",
          kind: "struct",
          members: [
            {
              name: "lot_id",
              type: "core::integer::u256",
              kind: "key",
            },
            {
              name: "final_report_hash",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "total_proceeds",
              type: "core::integer::u256",
              kind: "data",
            },
            {
              name: "settled_at",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "settled_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "shares_token",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "initial_weight_grams",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "final_weight_grams",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "weight_gain_grams",
              type: "core::integer::u32",
              kind: "data",
            },
            {
              name: "weight_gain_percentage",
              type: "core::integer::u16",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::settlement_registry::SettlementRegistry::ProtocolOperatorUpdated",
          kind: "struct",
          members: [
            {
              name: "old_operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "updated_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::settlement_registry::SettlementRegistry::LotFactoryUpdated",
          kind: "struct",
          members: [
            {
              name: "old_factory",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_factory",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "updated_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::settlement_registry::SettlementRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "ReentrancyGuardEvent",
              type: "openzeppelin_security::reentrancyguard::ReentrancyGuardComponent::Event",
              kind: "flat",
            },
            {
              name: "LotSettled",
              type: "contracts::settlement_registry::SettlementRegistry::LotSettled",
              kind: "nested",
            },
            {
              name: "ProtocolOperatorUpdated",
              type: "contracts::settlement_registry::SettlementRegistry::ProtocolOperatorUpdated",
              kind: "nested",
            },
            {
              name: "LotFactoryUpdated",
              type: "contracts::settlement_registry::SettlementRegistry::LotFactoryUpdated",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x13fce223d5ff6f359e3bfb904ec04aadda6b629e5627b0179f6f9e0f6e7b5b7",
    },
    AuditRegistry: {
      address:
        "0x52a5e383251e7e0b9775e521fad6e455ba061d84b2162248d07cf5828949a9b",
      abi: [
        {
          type: "impl",
          name: "AuditRegistryImpl",
          interface_name: "contracts::audit_registry::IAuditRegistry",
        },
        {
          type: "struct",
          name: "contracts::audit_registry::BatchAnchor",
          members: [
            {
              name: "batch_hash",
              type: "core::felt252",
            },
            {
              name: "from_ledger_id",
              type: "core::integer::u64",
            },
            {
              name: "to_ledger_id",
              type: "core::integer::u64",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::audit_registry::IAuditRegistry",
          items: [
            {
              type: "function",
              name: "anchor_batch",
              inputs: [
                {
                  name: "batch_id",
                  type: "core::integer::u64",
                },
                {
                  name: "batch_hash",
                  type: "core::felt252",
                },
                {
                  name: "from_ledger_id",
                  type: "core::integer::u64",
                },
                {
                  name: "to_ledger_id",
                  type: "core::integer::u64",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_operator",
              inputs: [
                {
                  name: "new_operator",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_batch",
              inputs: [
                {
                  name: "batch_id",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "contracts::audit_registry::BatchAnchor",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_anchored",
              inputs: [
                {
                  name: "batch_id",
                  type: "core::integer::u64",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_operator",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_batch_count",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_latest_batch_id",
              inputs: [],
              outputs: [
                {
                  type: "core::integer::u64",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_interfaces::access::ownable::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_interfaces::access::ownable::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "operator",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::audit_registry::AuditRegistry::BatchAnchored",
          kind: "struct",
          members: [
            {
              name: "batch_id",
              type: "core::integer::u64",
              kind: "key",
            },
            {
              name: "batch_hash",
              type: "core::felt252",
              kind: "data",
            },
            {
              name: "from_ledger_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "to_ledger_id",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "timestamp",
              type: "core::integer::u64",
              kind: "data",
            },
            {
              name: "anchored_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::audit_registry::AuditRegistry::OperatorUpdated",
          kind: "struct",
          members: [
            {
              name: "old_operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "new_operator",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
            {
              name: "updated_by",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::audit_registry::AuditRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "BatchAnchored",
              type: "contracts::audit_registry::AuditRegistry::BatchAnchored",
              kind: "nested",
            },
            {
              name: "OperatorUpdated",
              type: "contracts::audit_registry::AuditRegistry::OperatorUpdated",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x77ef4367c709775f661653a3c4da07bf3acd8499596f08602aacfb584bc0017",
    },
    YourContract: {
      address:
        "0x4069f8b61878874f7fc20259692b78f4a9e9555e11a155a09082c4a7b1ef149",
      abi: [
        {
          type: "impl",
          name: "YourContractImpl",
          interface_name: "contracts::your_contract::IYourContract",
        },
        {
          type: "struct",
          name: "core::byte_array::ByteArray",
          members: [
            {
              name: "data",
              type: "core::array::Array::<core::bytes_31::bytes31>",
            },
            {
              name: "pending_word",
              type: "core::felt252",
            },
            {
              name: "pending_word_len",
              type: "core::integer::u32",
            },
          ],
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::option::Option::<core::integer::u256>",
          variants: [
            {
              name: "Some",
              type: "core::integer::u256",
            },
            {
              name: "None",
              type: "()",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::your_contract::IYourContract",
          items: [
            {
              type: "function",
              name: "greeting",
              inputs: [],
              outputs: [
                {
                  type: "core::byte_array::ByteArray",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "set_greeting",
              inputs: [
                {
                  name: "new_greeting",
                  type: "core::byte_array::ByteArray",
                },
                {
                  name: "amount_strk",
                  type: "core::option::Option::<core::integer::u256>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "withdraw",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "premium",
              inputs: [],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableImpl",
          interface_name: "openzeppelin_access::ownable::interface::IOwnable",
        },
        {
          type: "interface",
          name: "openzeppelin_access::ownable::interface::IOwnable",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::your_contract::YourContract::GreetingChanged",
          kind: "struct",
          members: [
            {
              name: "greeting_setter",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_greeting",
              type: "core::byte_array::ByteArray",
              kind: "key",
            },
            {
              name: "premium",
              type: "core::bool",
              kind: "data",
            },
            {
              name: "value",
              type: "core::option::Option::<core::integer::u256>",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::your_contract::YourContract::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
            {
              name: "GreetingChanged",
              type: "contracts::your_contract::YourContract::GreetingChanged",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x73e64394744804c476eb7a4ad56902d49e77565ad413e6a34726b4914cc4d1b",
    },
  },
} as const;

export default deployedContracts;
